#[derive(Debug, Clone, PartialEq, Eq)]
#[allow(dead_code)]
#[non_exhaustive]
pub enum Token {
    Plus,
    Minus,
    Star,
    Percent,
    Slash,
    Equals,
    DoubleEquals,
    NotEquals,
    ExclamationMark,
    GreaterThan,
    LessThan,
    GreaterThanOrEqual,
    LessThanOrEqual,
    Assignment,
    String(String),
    Number(i64),
    Identifier(String),
    Boolean(bool),
    And,
    Or,
    Not,
    LeftParenthesis,
    RightParenthesis,
    LeftBrace,
    OpeningBracket,
    ClosingBracket,
    RightBrace,
    Comma,
    Semicolon,
    Let,
    Return,
    Cast,
    TypeAlias,
    Mod,
    EOF,
    /// Example: generic.ext-token.sized
    _ViaIdent(&'static str),
}
